export enum Regions {
  Vinnytsia = 'Вінницька',
  Volyn = 'Волинська',
  Dnipropetrovsk = 'Дніпропетровська',
  Donetsk = 'Донецька',
  Zhytomyr = 'Житомирська',
  Zakarpattia = 'Закарпатська',
  Zaporizhzhia = 'Запорізька',
  IvanoFrankivsk = 'Івано-Франківська',
  Kiev = 'Київська',
  Kirovohrad = 'Кіровоградська',
  Luhansk = 'Луганська',
  Lviv = 'Львівська',
  Mykolaiv = 'Миколаївська',
  Odessa = 'Одеська',
  Poltava = 'Полтавська',
  Rivne = 'Рівненська',
  Sumy = 'Сумська',
  Ternopil = 'Тернопільська',
  Kharkiv = 'Харківська',
  Kherson = 'Херсонська',
  Khmelnytskyi = 'Хмельницька',
  Cherkasy = 'Черкаська',
  Chernivtsi = 'Чернівецька',
  Chernihiv = 'Чернігівська',
  Crimea = 'АР Крим',
}
